---
- name: Post-deployment checks
  hosts: all
  become: yes
  tasks:
    - name: Check system health
      command: uptime

    - name: Check service status
      command: systemctl status "{{ item }}"
      loop:
        - ipa
        - foreman
        - openstack-*
        - ovirt-engine
        - prometheus
        - grafana
        - elasticsearch
        - td-agent
        - kibana